### ISSUE TITLE
Issue in the book (v1 and v2)

### ISSUE THREAD

**Issue by carlosgub** [thedrlambda/five-lines#2]
I'm here in the book 

![image](https://user-images.githubusercontent.com/30916886/86381063-7e44ce00-bc52-11ea-9fce-5418f20243cc.png)

and if you go to the section 5.5 

https://github.com/maxipaxi/five-lines/blob/section-5.5/index.ts

I see more differences between the class Stone and FallingStone. Can you help me with that. I don't know if this can be answered after pages but when I was in that page I feel confused :( 

![image](https://user-images.githubusercontent.com/30916886/86381298-c9f77780-bc52-11ea-9ace-2ceb3e771dad.png)

Cheers.

**Comment by thedrlambda** [comment]
Hi Carlos. Thanks for reaching out. 
It seems like you are completely right, I have somehow missed `moveHorizontal`. That is a major issue, I will have to do some thinking about how I can resolve this in the best way.

**Comment by carlosgub** [comment]
Thank you, right know after reading after pages. I know what you want to say, but before reading how you do the refactor I was little confused :). I had another problem later I put another issue but is typescript code problem :(.

**Comment by carlosgub** [comment]
@maxipaxi the typescript problem was my fault. Thanks for review my issue.
