### ISSUE TITLE
Not use your const variables

### ISSUE THREAD

**Issue by carlosgub** [thedrlambda/five-lines#3]
Hi, I was looking in section 6.3 and I saw this

https://github.com/maxipaxi/five-lines/blob/4cdf21fb152b3bb5a6fdf3ca9c3bd83a8858840e/index.ts#L365

You dont use your const variables on the window.addEventListener Listener :D. I don't know where you start to dont use it :).
 
```
const LEFT_KEY = 37;
const UP_KEY = 38;
const RIGHT_KEY = 39;
const DOWN_KEY = 40;
window.addEventListener("keydown", e => {
  if (e.keyCode === 37 || e.key === "a") inputs.push(new Left()); //HERE
  else if (e.keyCode === 38 || e.key === "w") inputs.push(new Up()); //HERE
  else if (e.keyCode === 39 || e.key === "d") inputs.push(new Right()); //HERE
  else if (e.keyCode === 40 || e.key === "s") inputs.push(new Down()); //HERE
});
```

**Comment by thedrlambda** [comment]
You have an amazing eye for detail, I am very thankful that you are using it on my book. I will fix this with the next push to the repo. Thank you!

**Comment by carlosgub** [comment]
Thank you 🤓🤓🤓.
